### ISSUE TITLE
403 error: Videos not loading

### ISSUE THREAD

**Issue by NoWorries** [tmobile/magentaA11y#12]
Hi, thanks for sharing this great resource! Have the videos stopped working recently, or has it been this way for a while?

They aren't loading and in console the response is: 
`Failed to load resource: the server responded with a status of 403 (Forbidden)`.

Modal page for reference:
https://www.a11yengineer.com/checklist-web/modal-dialog/

**Comment by brisourceful** [comment]
Hey Josh! I checked the videos for that URL in Firefox and Safari on MacOs and on iOS on Safari on cellular network and I'm seeing no issues. It's possible you checked the site while we had it under maintenance. Please let me know if you are still having issues.
