### ISSUE TITLE
Keyboard & focus: 404 Video example 

### ISSUE THREAD

**Issue by raleighvon** [tmobile/magentaA11y#148]
https://www.magentaa11y.com/how-to-test/keyboard-focus/

I started utilizing your examples for devs to reference on a project and noticed this wasn't working. 

<img width="1675" alt="image" src="https://github.com/user-attachments/assets/b8f52c37-d475-4d65-bec0-df802a2dc62b">

**Comment by marshcooke** [comment]
Thanks for calling this out, Raleigh! Seems like it was looking for a folder that no longer exists. We're working on resolving this with an [upcoming pull request](https://github.com/tmobile/magentaA11y/pull/159).

**Comment by marshcooke** [comment]
The ["How to test with the Keyboard" video](https://www.magentaa11y.com/how-to-test/keyboard-focus/) is back online, thanks again @raleighvon for calling out the issue!
