### ISSUE TITLE
Add MagentaA11y to the W3C tools list

### ISSUE THREAD

**Issue by josehilera** [tmobile/magentaA11y#23]
I am content manager of the [W3C Accessibility Evaluation Tools list.](https://www.w3.org/WAI/ER/tools/index.html). We have received a [request ](https://lists.w3.org/Archives/Public/public-wai-ert-tools/2022Jul/0002.html) to include Magenta11y in the list. According to the list management policy, we can only include the tool if the vendor agrees. Do you agree that we include it? In this case I need a contact email address to comment on some details.

**Comment by charlietriplett** [comment]
Of course — MagentaA11y is an open source tool and T-Mobile is happy to see it shared. 
Can I contact you via your uah.es email address?
