### ISSUE TITLE
Verify page button bugs

### ISSUE THREAD

**Issue by ryanve** [tmobile/magentaA11y#55]
### been unable to verify thru [twitter help](https://twitter.com/tMobilehelp) due to bugs on the `verify my account` page

* the form asks for `name` `phone` `pin/passcode` and the `submit` button has a `button-submit-disable` `class` preventing mouseclicks **even with valid form values**. am able to submit by keyboard tabbing to the button and pressing `return` **or** by removing the class thru the console first
* there seems to bee some caching issue because after reaching the success page your support team says i'm still unverified. tried many times over many days. these bugs have caused me a huge amount of time and pain as I imagine they have for other people
* the button is missing `:focus` styles. when a button has `:focus` it should have some [visual difference](https://www.w3.org/WAI/WCAG21/Understanding/focus-visible.html) such as an `outline` to help keyboard users recognize focus

**Comment by ryanve** [comment]
### semantic disabled

* the proper way to disable a `button` is thru the [<b>`disabled`</b> attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled)
* the proper way to style them is thru the `:disabled` selector to handle cases where a parent (element) is disabled

**Comment by charlietriplett** [comment]
Thank you @ryanve - we'll investigate that system with the owners.

**Comment by ryanve** [comment]
cooL Thanxyz @charlietriplett
